from tkinter import *
import tkinter as tk
from winsound import *

root = tk.Tk()
root.title("The Blazin' Chords")
root.geometry('700x350')
root.configure(background='dark blue')

#start of the gutiar 
randombox = Button(bg = "white", width = 65, height = 11)
randombox.pack()
randombox.place(x=120, y=0)


guitarHighstring = lambda: PlaySound('GuitarHighE.wav', SND_FILENAME)
gutiarstring1 = Button(bg = "#FF0000", width = 60, height = 1, text="e", fg = "white", command = guitarHighstring)
gutiarstring1.pack()
bstringsound = lambda: PlaySound('GuitarBString.wav', SND_FILENAME)
gutiarstring2 = Button(bg = "#FF1212", width = 60, height = 1, text = "b", fg = "white", command = bstringsound)
gutiarstring2.pack()
gstringnote = lambda: PlaySound('GuitarGString.wav', SND_FILENAME)
gutiarstring3 = Button(bg = "#FF3636", width = 60, height = 1, text = "g", fg = "white", command = gstringnote)
gutiarstring3.pack()
dstringnote = lambda: PlaySound('GuitarDString.wav', SND_FILENAME)
gutiarstring4 = Button(bg = "#FF5151", width = 60, height = 1, text = "d", fg = "white", command = dstringnote)
gutiarstring4.pack()
astringnote = lambda: PlaySound('GuitarAString.wav', SND_FILENAME)
gutiarstring5 = Button(bg = "#FF6666", width = 60, height = 1, text = "a", fg = "white", command = astringnote)
gutiarstring5.pack()
estringnote = lambda: PlaySound('GuitarLow-E.wav', SND_FILENAME)
gutiarstring6 = Button(bg = "#FF7575", width = 60, height = 1, text = "E", fg = "white", command = estringnote)  
gutiarstring6.pack()
randombox1 = Button(bg = "black", width = 60, height = 9)
randombox1.pack()
randombox1.place(x=136, y=220)

cnotesound = lambda: PlaySound('cNote.wav', SND_FILENAME)
button1 = Button(bg= "white", relief = "solid", width = 5, height = 6, text = "C", font = "Arial", command = cnotesound)
button1.pack()
button1.place(x=165, y=250)
dnotesound = lambda: PlaySound('dNote.wav', SND_FILENAME)
button2 = Button(bg= "white", relief = "solid", width = 5, height = 6, text = "D", font = "Arial", command = dnotesound)
button2.pack()
button2.place(x=218, y=250)
enotesound = lambda: PlaySound('eNote.wav', SND_FILENAME)
button3 = Button(bg= "white", relief = "solid", width = 5, height = 6, text = "E", font = "Arial", command = enotesound)
button3.pack()
button3.place(x=271, y=250)
fnotesound = lambda: PlaySound('fNote.wav', SND_FILENAME)
button4 = Button(bg= "white", relief = "solid", width = 5, height = 6, text = "F", font = "Arial", command = fnotesound)
button4.pack()
button4.place(x=324, y=250)
gnotesound = lambda: PlaySound('gNote.wav', SND_FILENAME)
button5 = Button(bg= "white", relief = "solid", width = 5, height = 6, text = "G", font = "Arial", command = gnotesound)
button5.pack()
button5.place(x=377, y=250)
anotesound = lambda: PlaySound('aNote.wav', SND_FILENAME)
button6 = Button(bg= "white", relief = "solid", width = 5, height = 6, text = "A", font = "Arial", command = anotesound)
button6.pack()
button6.place(x=430, y=250)
bnotesound = lambda: PlaySound('bNote.wav', SND_FILENAME)
button7 = Button(bg= "white", relief = "solid", width = 5, height = 6, text = "B", font = "Arial", command = bnotesound)
button7.pack()
button7.place(x=483, y=250)
# these are the small black ones
csharpsound = lambda: PlaySound('c#.wav', SND_FILENAME)
button1A = Button(bg = "black", width = 2, height = 3, text = "C#", font = "Arial", fg = "white", command = csharpsound)
button1A.pack()
button1A.place(x=207, y=250)
dsharpsound = lambda: PlaySound('d#.wav', SND_FILENAME)
button2A = Button(bg = "black", width = 2, height = 3, text = "D#", font = "Arial", fg = "white", command = dsharpsound)
button2A.pack()
button2A.place(x=260, y=250)
fsharpsound = lambda: PlaySound('f#.wav', SND_FILENAME)
button3A = Button(bg = "black", width = 2, height = 3, text = "F#", font = "Arial", fg = "white", command = fsharpsound)
button3A.pack()
button3A.place(x=420, y=250)
gsharpsound = lambda: PlaySound('g#.wav', SND_FILENAME)
button4A = Button(bg = "black", width = 2, height = 3, text = "G#", font = "Arial", fg = "white", command = gsharpsound)
button4A.pack()
button4A.place(x=365, y=250)
asharpsound = lambda: PlaySound('a#.wav', SND_FILENAME)
button5A = Button(bg = "black", width = 2, height = 3, text = "A#", font = "Arial", fg = "white", command = asharpsound)
button5A.pack()
button5A.place(x=475, y=250)

#the drumpad
greybox = Button(bg = "grey", width = 9, height = 8 )
greybox.pack()
greybox.place(x = 610, y = 103)
greybox1 = Button(bg = "grey", width = 9, height = 8 )
greybox1.pack()
greybox1.place(x = 22, y = 103)
snaresound = lambda: PlaySound('snare.wav', SND_FILENAME)
drumpad1 = Button(bg = "red", width = 5, height = 2, text = "snare", font = "Arial", fg = "white", command = snaresound)
drumpad1.pack()
drumpad1.place(x = 30, y = 120)
kicksound = lambda: PlaySound('kick.wav', SND_FILENAME)
drumpad2 = Button(bg = "white", width = 5, height = 2, text = "kick", font = "Arial", fg = "black", command = kicksound)
drumpad2.pack()
drumpad2.place(x = 30, y = 170)
cymbolsound = lambda: PlaySound('cymbol.wav', SND_FILENAME)
drumpad3 = Button(bg = "white", width = 5, height = 2, text = "cymbol", font = "Arial", fg = "black", command = cymbolsound)
drumpad3.pack()
drumpad3.place(x = 618, y = 120)
drumsound = lambda: PlaySound('tom.wav', SND_FILENAME)
drumpad4 = Button(bg = "red", width = 5, height = 2, text = "drum", font = "Arial", fg = "white", command = drumsound)
drumpad4.pack()
drumpad4.place(x = 618, y = 170)

#playback button
playback = Button(bg = "grey", width = 7, height = 1, text = "playback", font = "Arial", fg = "black")
playback.pack()
playback.place(x = 609, y = 7)
record = Button(bg = "grey", width = 7, height = 1, text = "record", font = "Arial", fg = "black")
record.pack()
record.place(x = 9, y = 7)

root.mainloop()